//////////////////////////////////////////////////////////////////////
//
//  This pipeline builds a helm chart
//
//////////////////////////////////////////////////////////////////////

pipeline {
    agent {
        kubernetes { label 'helmfile-git' }
    }

    options {
        // Add time stamps to build output
        timestamps()
    }

    environment {
        ARTIFACTORY_CREDENTIALS = 'asynchrony_generic'
        BUILD_JOB_TOKEN = 'iAmTheWalrus'
    }

    stages {
        // Create the Jenkins master
        stage('Lint') {
            steps {
                container('helmfile') {
                    ansiColor('xterm') {
                        sh '''
                        helm lint . 
                        '''
                    }
                }
            }
        }
        stage('Build') {
            steps {
                container('helmfile') {
                    ansiColor('xterm') {
                        sh '''
                        helm package .
                        '''
                    }
                }
            }
        }
        stage('Push Helm Chart to Artifactory') {
            steps {
                container('helmfile') {
                    ansiColor('xterm') {
                        script {
                            withCredentials([usernameColonPassword(credentialsId: ARTIFACTORY_CREDENTIALS, variable: 'CREDS')]) {
                                def datas = readYaml file: 'Chart.yaml'
                                artifact = "${datas.name}-${datas.version}.tgz"
                                sh "curl -u\"${CREDS}\" -T ${artifact} \"https://artifactory.company.com/artifactory/helm-local/${artifact}\""
                            }
                        }
                    }
                }
            }    
        }
    }
}